repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        stages: [pre-commit]
        files:
          (?x)^(
          README.md$|
          )$
